version: '3.8'
services:
   postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=simple_bank
   api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mysecret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
